merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('about-us/', views.about),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('contact-us/', views.contact),
]

listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    class Genre(models.TextChoices):
        ALTERNATIVE_ROCK = 'AR'
        ROCK = 'RK'
        POP_ROCK = 'PR'
        SOFT_ROCK = 'SR'

    name = models.fields.CharField(max_length=50)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[
            MinValueValidator(1000),
            MaxValueValidator(2024),
        ]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = 'REC'
        CLOTHING = 'CLO'
        POSTERS = 'POS'
        MISCELLANEOUS = 'MSC'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=True)
    year = models.fields.IntegerField(
        validators=[
            MinValueValidator(1900),
            MaxValueValidator(2024),
        ],
        null=True,
        blank=True,
    )
    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(
        Band,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f'{self.title}'

listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from listings.models import Band, Listing


def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands},)


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band},)


def about(request):
    return render(request,
                  'listings/about.html',)


def listing_list(request):
    listings = Listing.objects.all()
    return render(request,
                  'listings/listing_list.html',
                  {'listings': listings},)


def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request,
                  'listings/listing_detail.html',
                  {'listing': listing},)


def contact(request):
    return render(request,
                  'listings/contact.html',)

listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>About Us</h1>
    <p>We love merch!</p>
{% endblock %}

listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2>{{ band.name }}</h2>

    <ul>
        <li>Genre: {{ band.get_genre_display }}</li>
        <li>Year formed: {{ band.year_formed }}</li>
        <li>Active: {{ band.active|yesno }}</li>
        {% if band.official_homepage %}
            <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
        {% endif %}
        <li>Biography: {{ band.biography }}</li>
        <li>Listings
            <ul>
                {% for listing in band.listing_set.all %}
                <li>{{ listing.title }}</li>
                {% endfor %}
            </ul>
        </li>
        <p><a href="{% url 'band-list' %}">Back to all Bands</a></p>
    </ul>
{% endblock %}

listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Bands</h1>
    <ul>
        {% for band in bands %}
            <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

listings/templates/listings/base.html
<!DOCTYPE html>
    {% load static %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}">
    </head>
    <body>
        <nav>
            <li><a href="{% url 'band-list' %}">Bands</a></li>
            <li><a href="{% url 'listing-list' %}">Listings</a></li>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Contact Us</h1>
    <p>We'd love to hear from you!</p>
{% endblock %}

listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Hello Django!</h1>
    <p>My favorite bands are:</p>
    <ul>
        {% for band in bands %}
            <li>
                {{ band.name }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2>{{ listing.title }}</h2>

    <ul>
        <li>Description: {{ listing.description }}</li>
        <li>Sold: {{ listing.sold|yesno }}</li>
        <li>Year: {{ listing.year }}</li>
        <li>Type: {{ listing.get_type_display }}</li>
        <li>Band: {{ listing.band.name }}</li>
        <p><a href="{% url 'listing-list' %}">Back to all Listings</a></p>
    </ul>
{% endblock %}

listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Listings</h1>
    <ul>
        {% for listing in listings %}
            <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Hello Django!</h1>
    <p>The available merch listings are:</p>
    <ul>
        {% for listing in listings %}
            <li>{{ listing.title }}</li>
        {% endfor %}
    </ul>
{% endblock %}